public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int freezing=-35968;
        byte box=50;
        short cars=240;
        long depth=-32564568521L;
        float length=25.135f;
        double width=45.689;
        System.out.println("Значение переменной freezing с типом int равно " + freezing);
        System.out.println("Значение переменной box с типом byte равно " + box);
        System.out.println("Значение переменной cars с типом short равно " + cars);
        System.out.println("Значение переменной depth с типом long равно " + depth);
        System.out.println("Значение переменной length с типом float равно " + length);
        System.out.println("Значение переменной width с типом double равно " + width);
        System.out.println("Задача 2");
        float v=27.12f;
        System.out.println(v);
        long way=987_678_965_549L;
        System.out.println(way);
        float swimming=2.786f;
        System.out.println(swimming);
        short seconds=569;
        System.out.println(seconds);
        short cake=-159;
        System.out.println(cake);
        short sand=27897;
        System.out.println(sand);
        byte book=67;
        System.out.println(book);
        System.out.println("Задача 3");
        byte studentLudmila=23;
        byte studentAnna=27;
        byte studentEkaterina=30;
        short paper=480;
        short oneStudentPaper= (short) (paper/(studentLudmila+studentAnna+studentEkaterina));
        System.out.println("На каждого ученика рассчитано " +oneStudentPaper+ " листов бумаги");
        System.out.println("Задача 4");
        byte botlMake=16;
        byte timeMake=2;
        short timeMake20=(short)(20/timeMake);
        short botlMake20=(short)(botlMake*timeMake20);
        System.out.println("За 20 минут машина произвела "+botlMake20+ " штук бутылок");
        short timeDay=(short) (24*60);
        short botlMakeDay=(short)(timeDay/timeMake*botlMake);
        System.out.println("За сутки машина произвела "+botlMakeDay+ " штук бутылок");
        int botlMakeThreeDay=botlMakeDay*3;
        System.out.println("За три дня машина произвела "+botlMakeThreeDay+ " штук бутылок");
        int botlMakeOneMonth=botlMakeDay*31;
        System.out.println("За месяц машина произвела "+botlMakeOneMonth+ " штук бутылок");
        System.out.println("Задача 5");
        byte whitePaint=2;
        byte brownPaint=4;
        byte allPaint=120;
        byte schoolRoom=(byte)(allPaint/(whitePaint+brownPaint));
        byte allwhitePaint=(byte)(schoolRoom*whitePaint);
        byte allbrownPaint=(byte)(schoolRoom*brownPaint);
        System.out.println("В школе, где "+schoolRoom+ " классов, нужно " +allwhitePaint+" банок белой краски и "+allbrownPaint+" банок коричневой краски");
        System.out.println("Задача 6");
        byte banana= (byte) (5*80);
        short milk=(short)(2*105);
        short iceCream=(short) (2*100);
        short eggs=(short)(4*70);
        float breakfest=(float) (banana+milk+iceCream+eggs);
        System.out.println("Вес завтрака "+breakfest+" грамм");
        float breakfestKg=breakfest/1000;
        System.out.println("Вес завтрака "+breakfestKg+" килограмм");
        System.out.println("Задача 7");
        short badWeight=(short) (7*1000);
        short firstProgram=(short) (badWeight/250);
        short secondProgram=(short) (badWeight/500);
        short averageDay=(short)((firstProgram+secondProgram)/2);
        System.out.println("Если спортсмен будет терять каждый день по 250 грамм то уйдет "+firstProgram+" дней, если спортсмен будет терять каждый день по 500 грамм то уйдет "+secondProgram+" дней, в среднем похуденее займет "+averageDay+" дней");
        System.out.println("Задача 8");
        int moneyMasha=67760;
        float surplusMasha=(float)(moneyMasha*1.1);
        float yearsurplusMasha= surplusMasha*12-moneyMasha*12;
        System.out.println("Маша теперь получает "+surplusMasha+" рублей. Годовой доход вырос на "+yearsurplusMasha+" рублей");
        int moneyDenis=83690;
        float surplusDenis=(float)(moneyDenis*1.1);
        float yearsurplusDenis=surplusDenis*12-moneyDenis*12;
        System.out.println("Денис теперь получает "+surplusDenis+" рублей. Годовой доход вырос на "+yearsurplusDenis+" рублей");
        int moneyKristina=76230;
        float surplusKristina=(float)(moneyKristina*1.1);
        float yearsurplusKristina= surplusKristina*12-moneyKristina*12;
        System.out.println("Кристина теперь получает "+surplusKristina+" рублей. Годовой доход вырос на "+yearsurplusKristina+" рублей");

    }
}